### ISSUE TITLE
Command "cd" don't produce effects when executed by ".term"

### ISSUE THREAD

**Issue by x0rzavi** [fortifying/OUBnew#10]
I tried "cd .." as usual. Even after getting reported that the command executed successfully, on executing "ls" again, it reported "/root/userbot" directory. While, again when I tried "ls /" I was able to get the desirable output.

**Comment by fortifying** [comment]
This error is not from userbot. just error from heroku. try to do that again in a few hours. check errors: status.heroku.com

**Comment by x0rzavi** [comment]
OK thanks

**Comment by adislice** [comment]
Use oneline command if you want to do something after changing directory. 
`.term cd .. && touch file.txt && echo "sometext" >> file.txt`

**Comment by fortifying** [comment]
just .term ls (dir) and everything solved. no need to do cd on userbot terminal.
case closed
